/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zamil
 */
public class Application extends javax.swing.JFrame {

    Queue queue = new Queue();
    Stack counter1 = new Stack();
    Stack counter2 = new Stack();
    Stack counter3 = new Stack();
    Stack counter4 = new Stack();
    int ticket;
    String ticketNum;
    
    /**
     * Creates new form CustomerView
     */
    public Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTab = new javax.swing.JTabbedPane();
        cvPanel = new javax.swing.JPanel();
        cv_counter2 = new javax.swing.JDesktopPane();
        counter_2_status = new javax.swing.JLabel();
        counter_2_label = new javax.swing.JLabel();
        counter_2_num = new javax.swing.JLabel();
        numberTicket = new javax.swing.JDesktopPane();
        numButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        latest_serving_num = new javax.swing.JLabel();
        last_issued_num = new javax.swing.JLabel();
        cv_counter3 = new javax.swing.JDesktopPane();
        counter_3_status = new javax.swing.JLabel();
        counter_3_label = new javax.swing.JLabel();
        counter_3_num = new javax.swing.JLabel();
        cv_counter1 = new javax.swing.JDesktopPane();
        counter_1_status = new javax.swing.JLabel();
        counter_1_label = new javax.swing.JLabel();
        counter_1_num = new javax.swing.JLabel();
        cv_counter4 = new javax.swing.JDesktopPane();
        counter_4_status = new javax.swing.JLabel();
        counter_4_label = new javax.swing.JLabel();
        counter_4_num = new javax.swing.JLabel();
        cmPanel = new javax.swing.JPanel();
        cm_counter1 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        goOffline1 = new javax.swing.JToggleButton();
        comp_curr1 = new javax.swing.JButton();
        next1 = new javax.swing.JButton();
        cm_counter2 = new javax.swing.JDesktopPane();
        jLabel12 = new javax.swing.JLabel();
        goOffline2 = new javax.swing.JToggleButton();
        comp_curr2 = new javax.swing.JButton();
        next2 = new javax.swing.JButton();
        cm_counter3 = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        goOffline3 = new javax.swing.JToggleButton();
        comp_curr3 = new javax.swing.JButton();
        next3 = new javax.swing.JButton();
        cm_counter4 = new javax.swing.JDesktopPane();
        jLabel14 = new javax.swing.JLabel();
        goOffline4 = new javax.swing.JToggleButton();
        comp_curr4 = new javax.swing.JButton();
        next4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticketing Application");

        cv_counter2.setBackground(new java.awt.Color(255, 255, 255));
        cv_counter2.setPreferredSize(new java.awt.Dimension(177, 100));

        counter_2_status.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        counter_2_status.setForeground(java.awt.Color.green);
        counter_2_status.setText("•");

        counter_2_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        counter_2_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_2_label.setText("Counter 2");

        counter_2_num.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        counter_2_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_2_num.setText("<cur_num>");

        javax.swing.GroupLayout cv_counter2Layout = new javax.swing.GroupLayout(cv_counter2);
        cv_counter2.setLayout(cv_counter2Layout);
        cv_counter2Layout.setHorizontalGroup(
            cv_counter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cv_counter2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cv_counter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(counter_2_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cv_counter2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(counter_2_status))
                    .addComponent(counter_2_num, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );
        cv_counter2Layout.setVerticalGroup(
            cv_counter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cv_counter2Layout.createSequentialGroup()
                .addComponent(counter_2_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counter_2_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counter_2_num)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        cv_counter2.setLayer(counter_2_status, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cv_counter2.setLayer(counter_2_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cv_counter2.setLayer(counter_2_num, javax.swing.JLayeredPane.DEFAULT_LAYER);

        numberTicket.setBackground(new java.awt.Color(204, 204, 204));
        numberTicket.setForeground(new java.awt.Color(255, 255, 51));

        numButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        numButton.setText("Take a Number");
        numButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Now Serving: ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Last Number:");

        latest_serving_num.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        latest_serving_num.setText("<latest_serving_num>");

        last_issued_num.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        last_issued_num.setText("<last_issued_num>");

        javax.swing.GroupLayout numberTicketLayout = new javax.swing.GroupLayout(numberTicket);
        numberTicket.setLayout(numberTicketLayout);
        numberTicketLayout.setHorizontalGroup(
            numberTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberTicketLayout.createSequentialGroup()
                .addGroup(numberTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(numberTicketLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(numberTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(numberTicketLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(latest_serving_num))
                            .addGroup(numberTicketLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(last_issued_num))))
                    .addGroup(numberTicketLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(numButton)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        numberTicketLayout.setVerticalGroup(
            numberTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberTicketLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(numberTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(latest_serving_num))
                .addGap(18, 18, 18)
                .addGroup(numberTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(last_issued_num))
                .addGap(18, 18, 18)
                .addComponent(numButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        numberTicket.setLayer(numButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        numberTicket.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        numberTicket.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        numberTicket.setLayer(latest_serving_num, javax.swing.JLayeredPane.DEFAULT_LAYER);
        numberTicket.setLayer(last_issued_num, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cv_counter3.setBackground(new java.awt.Color(255, 255, 255));
        cv_counter3.setPreferredSize(new java.awt.Dimension(177, 100));

        counter_3_status.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        counter_3_status.setForeground(java.awt.Color.green);
        counter_3_status.setText("•");

        counter_3_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        counter_3_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_3_label.setText("Counter 3");

        counter_3_num.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        counter_3_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_3_num.setText("<cur_num>");

        javax.swing.GroupLayout cv_counter3Layout = new javax.swing.GroupLayout(cv_counter3);
        cv_counter3.setLayout(cv_counter3Layout);
        cv_counter3Layout.setHorizontalGroup(
            cv_counter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cv_counter3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cv_counter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cv_counter3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(counter_3_status))
                    .addComponent(counter_3_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(counter_3_num, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );
        cv_counter3Layout.setVerticalGroup(
            cv_counter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cv_counter3Layout.createSequentialGroup()
                .addComponent(counter_3_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counter_3_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counter_3_num)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        cv_counter3.setLayer(counter_3_status, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cv_counter3.setLayer(counter_3_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cv_counter3.setLayer(counter_3_num, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cv_counter1.setBackground(new java.awt.Color(255, 255, 255));
        cv_counter1.setPreferredSize(new java.awt.Dimension(177, 100));

        counter_1_status.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        counter_1_status.setForeground(java.awt.Color.green);
        counter_1_status.setText("•");

        counter_1_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        counter_1_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_1_label.setText("Counter 1");

        counter_1_num.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        counter_1_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_1_num.setText("<cur_num>");

        javax.swing.GroupLayout cv_counter1Layout = new javax.swing.GroupLayout(cv_counter1);
        cv_counter1.setLayout(cv_counter1Layout);
        cv_counter1Layout.setHorizontalGroup(
            cv_counter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cv_counter1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cv_counter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cv_counter1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(counter_1_status))
                    .addComponent(counter_1_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(counter_1_num, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );
        cv_counter1Layout.setVerticalGroup(
            cv_counter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cv_counter1Layout.createSequentialGroup()
                .addComponent(counter_1_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counter_1_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counter_1_num)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        cv_counter1.setLayer(counter_1_status, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cv_counter1.setLayer(counter_1_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cv_counter1.setLayer(counter_1_num, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cv_counter4.setBackground(new java.awt.Color(255, 255, 255));
        cv_counter4.setPreferredSize(new java.awt.Dimension(177, 100));

        counter_4_status.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        counter_4_status.setForeground(java.awt.Color.green);
        counter_4_status.setText("•");

        counter_4_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        counter_4_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_4_label.setText("Counter 4");

        counter_4_num.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        counter_4_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_4_num.setText("<cur_num>");

        javax.swing.GroupLayout cv_counter4Layout = new javax.swing.GroupLayout(cv_counter4);
        cv_counter4.setLayout(cv_counter4Layout);
        cv_counter4Layout.setHorizontalGroup(
            cv_counter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cv_counter4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cv_counter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cv_counter4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(counter_4_status))
                    .addComponent(counter_4_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(counter_4_num, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );
        cv_counter4Layout.setVerticalGroup(
            cv_counter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cv_counter4Layout.createSequentialGroup()
                .addComponent(counter_4_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counter_4_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counter_4_num)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        cv_counter4.setLayer(counter_4_status, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cv_counter4.setLayer(counter_4_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cv_counter4.setLayer(counter_4_num, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout cvPanelLayout = new javax.swing.GroupLayout(cvPanel);
        cvPanel.setLayout(cvPanelLayout);
        cvPanelLayout.setHorizontalGroup(
            cvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numberTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(cvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cv_counter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cv_counter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cv_counter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cv_counter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cvPanelLayout.setVerticalGroup(
            cvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cvPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(numberTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cv_counter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cv_counter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cv_counter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cv_counter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menuTab.addTab("Customer View", cvPanel);

        cm_counter1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Counter 1");

        goOffline1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        goOffline1.setText("Go Offline");
        goOffline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goOffline1ActionPerformed(evt);
            }
        });

        comp_curr1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comp_curr1.setText("Complete Current");
        comp_curr1.setEnabled(false);
        comp_curr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_curr1ActionPerformed(evt);
            }
        });

        next1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        next1.setText("Call Next");
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cm_counter1Layout = new javax.swing.GroupLayout(cm_counter1);
        cm_counter1.setLayout(cm_counter1Layout);
        cm_counter1Layout.setHorizontalGroup(
            cm_counter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cm_counter1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cm_counter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(next1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comp_curr1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goOffline1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cm_counter1Layout.setVerticalGroup(
            cm_counter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cm_counter1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goOffline1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comp_curr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next1)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        cm_counter1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter1.setLayer(goOffline1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter1.setLayer(comp_curr1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter1.setLayer(next1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cm_counter2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Counter 2");

        goOffline2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        goOffline2.setText("Go Offline");
        goOffline2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goOffline2ActionPerformed(evt);
            }
        });

        comp_curr2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comp_curr2.setText("Complete Current");
        comp_curr2.setEnabled(false);
        comp_curr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_curr2ActionPerformed(evt);
            }
        });

        next2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        next2.setText("Call Next");
        next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cm_counter2Layout = new javax.swing.GroupLayout(cm_counter2);
        cm_counter2.setLayout(cm_counter2Layout);
        cm_counter2Layout.setHorizontalGroup(
            cm_counter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cm_counter2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cm_counter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comp_curr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goOffline2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cm_counter2Layout.setVerticalGroup(
            cm_counter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cm_counter2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goOffline2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comp_curr2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next2)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        cm_counter2.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter2.setLayer(goOffline2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter2.setLayer(comp_curr2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter2.setLayer(next2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cm_counter3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Counter 3");

        goOffline3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        goOffline3.setText("Go Offline");
        goOffline3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goOffline3ActionPerformed(evt);
            }
        });

        comp_curr3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comp_curr3.setText("Complete Current");
        comp_curr3.setEnabled(false);
        comp_curr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_curr3ActionPerformed(evt);
            }
        });

        next3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        next3.setText("Call Next");
        next3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cm_counter3Layout = new javax.swing.GroupLayout(cm_counter3);
        cm_counter3.setLayout(cm_counter3Layout);
        cm_counter3Layout.setHorizontalGroup(
            cm_counter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cm_counter3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cm_counter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comp_curr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goOffline3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cm_counter3Layout.setVerticalGroup(
            cm_counter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cm_counter3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goOffline3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comp_curr3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next3)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        cm_counter3.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter3.setLayer(goOffline3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter3.setLayer(comp_curr3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter3.setLayer(next3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cm_counter4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Counter 4");

        goOffline4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        goOffline4.setText("Go Offline");
        goOffline4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goOffline4ActionPerformed(evt);
            }
        });

        comp_curr4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comp_curr4.setText("Complete Current");
        comp_curr4.setEnabled(false);
        comp_curr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_curr4ActionPerformed(evt);
            }
        });

        next4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        next4.setText("Call Next");
        next4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cm_counter4Layout = new javax.swing.GroupLayout(cm_counter4);
        cm_counter4.setLayout(cm_counter4Layout);
        cm_counter4Layout.setHorizontalGroup(
            cm_counter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cm_counter4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cm_counter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comp_curr4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goOffline4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cm_counter4Layout.setVerticalGroup(
            cm_counter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cm_counter4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goOffline4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comp_curr4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next4)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        cm_counter4.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter4.setLayer(goOffline4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter4.setLayer(comp_curr4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        cm_counter4.setLayer(next4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout cmPanelLayout = new javax.swing.GroupLayout(cmPanel);
        cmPanel.setLayout(cmPanelLayout);
        cmPanelLayout.setHorizontalGroup(
            cmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cm_counter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cm_counter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cm_counter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cm_counter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cmPanelLayout.setVerticalGroup(
            cmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cm_counter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cm_counter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cm_counter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cm_counter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuTab.addTab("Counter Management", cmPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuTab, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButtonActionPerformed
        ticket++;
        ticketNum = String.format("%04d", ticket);
        last_issued_num.setText(queue.enqueue(ticketNum));
    }//GEN-LAST:event_numButtonActionPerformed

    private void goOffline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goOffline1ActionPerformed
        if (goOffline1.isSelected()) {
            goOffline1.setText("Go Online");
            counter_1_status.setForeground(java.awt.Color.gray);
            cv_counter1.setBackground(new java.awt.Color(204, 204, 204));
            counter_1_num.setFont(new java.awt.Font("Arial", 2, 14));
            counter_1_num.setText("Offline");
            next1.setEnabled(false);
        } else {
            goOffline1.setText("Go Offline");
            counter_1_status.setForeground(java.awt.Color.green);
            cv_counter1.setBackground(new java.awt.Color(255, 255, 255));
            counter_1_num.setFont(new java.awt.Font("Arial", 0, 14));
            counter_1_num.setText("Vacant");
            next1.setEnabled(true);
        }
    }//GEN-LAST:event_goOffline1ActionPerformed

    private void goOffline2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goOffline2ActionPerformed
        if (goOffline2.isSelected()) {
            goOffline2.setText("Go Online");
            counter_2_status.setForeground(java.awt.Color.gray);
            cv_counter2.setBackground(new java.awt.Color(204, 204, 204));
            counter_2_num.setFont(new java.awt.Font("Arial", 2, 14));
            counter_2_num.setText("Offline");
            next2.setEnabled(false);
        } else {
            goOffline2.setText("Go Offline");
            counter_2_status.setForeground(java.awt.Color.green);
            cv_counter2.setBackground(new java.awt.Color(255, 255, 255));
            counter_2_num.setFont(new java.awt.Font("Arial", 0, 14));
            counter_2_num.setText("Vacant");
            next2.setEnabled(true);
        }
    }//GEN-LAST:event_goOffline2ActionPerformed

    private void goOffline3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goOffline3ActionPerformed
        if (goOffline3.isSelected()) {
            goOffline3.setText("Go Online");
            counter_3_status.setForeground(java.awt.Color.gray);
            cv_counter3.setBackground(new java.awt.Color(204, 204, 204));
            counter_3_num.setFont(new java.awt.Font("Arial", 2, 14));
            counter_3_num.setText("Offline");
            next3.setEnabled(false);
        } else {
            goOffline3.setText("Go Offline");
            counter_3_status.setForeground(java.awt.Color.green);
            cv_counter3.setBackground(new java.awt.Color(255, 255, 255));
            counter_3_num.setFont(new java.awt.Font("Arial", 0, 14));
            counter_3_num.setText("Vacant");
            next3.setEnabled(true);
        }
    }//GEN-LAST:event_goOffline3ActionPerformed

    private void goOffline4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goOffline4ActionPerformed
        if (goOffline4.isSelected()) {
            goOffline4.setText("Go Online");
            counter_4_status.setForeground(java.awt.Color.gray);
            cv_counter4.setBackground(new java.awt.Color(204, 204, 204));
            counter_4_num.setFont(new java.awt.Font("Arial", 2, 14));
            counter_4_num.setText("Vacant");
            next4.setEnabled(false);
        } else {
            goOffline4.setText("Go Offline");
            counter_4_status.setForeground(java.awt.Color.green);
            cv_counter4.setBackground(new java.awt.Color(255, 255, 255));
            counter_4_num.setFont(new java.awt.Font("Arial", 0, 14));
            counter_4_num.setText("Vacant");
            next4.setEnabled(true);
        }
    }//GEN-LAST:event_goOffline4ActionPerformed

    private void comp_curr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_curr1ActionPerformed
        counter1.dequeue();
        counter_1_status.setForeground(java.awt.Color.green);
        comp_curr1.setEnabled(false);
        goOffline1.setEnabled(true);
        next1.setEnabled(true);
        counter_1_num.setText("Vacant");
    }//GEN-LAST:event_comp_curr1ActionPerformed

    private void comp_curr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_curr2ActionPerformed
        counter2.dequeue();
        counter_2_status.setForeground(java.awt.Color.green);
        comp_curr2.setEnabled(false);
        goOffline2.setEnabled(true);
        next2.setEnabled(true);
        counter_2_num.setText("Vacant");
    }//GEN-LAST:event_comp_curr2ActionPerformed

    private void comp_curr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_curr3ActionPerformed
        counter3.dequeue();
        counter_3_status.setForeground(java.awt.Color.green);
        comp_curr3.setEnabled(false);
        goOffline3.setEnabled(true);
        next3.setEnabled(true);
        counter_3_num.setText("Vacant");
    }//GEN-LAST:event_comp_curr3ActionPerformed

    private void comp_curr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_curr4ActionPerformed
        counter4.dequeue();
        counter_4_status.setForeground(java.awt.Color.green);
        comp_curr4.setEnabled(false);
        goOffline4.setEnabled(true);
        next4.setEnabled(true);
        counter_4_num.setText("Vacant");
    }//GEN-LAST:event_comp_curr4ActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        if (queue.size() == 0)
            javax.swing.JOptionPane.showMessageDialog(null, "No tickets in the waiting queue");
        else {
            String counter_1_num_ticket = queue.dequeue();
            counter1.enqueue(counter_1_num_ticket);
            counter_1_num.setText(counter_1_num_ticket);
            latest_serving_num.setText(counter_1_num_ticket);
            counter_1_status.setForeground(java.awt.Color.red);
            comp_curr1.setEnabled(true);
            goOffline1.setEnabled(false);
            next1.setEnabled(false);
        }
    }//GEN-LAST:event_next1ActionPerformed

    private void next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next2ActionPerformed
        if (queue.size() == 0)
            javax.swing.JOptionPane.showMessageDialog(null, "No tickets in the waiting queue");
        else {
            String counter_2_num_ticket = queue.dequeue();
            counter2.enqueue(counter_2_num_ticket);
            counter_2_num.setText(counter_2_num_ticket);
            latest_serving_num.setText(counter_2_num_ticket);
            counter_2_status.setForeground(java.awt.Color.red);
            comp_curr2.setEnabled(true);
            goOffline2.setEnabled(false);
            next2.setEnabled(false);
        }
    }//GEN-LAST:event_next2ActionPerformed

    private void next3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next3ActionPerformed
        if (queue.size() == 0)
            javax.swing.JOptionPane.showMessageDialog(null, "No tickets in the waiting queue");
        else {
            String counter_3_num_ticket = queue.dequeue();
            counter3.enqueue(counter_3_num_ticket);
            counter_3_num.setText(counter_3_num_ticket);
            latest_serving_num.setText(counter_3_num_ticket);
            counter_3_status.setForeground(java.awt.Color.red);
            comp_curr3.setEnabled(true);
            goOffline3.setEnabled(false);
            next3.setEnabled(false);
        }
    }//GEN-LAST:event_next3ActionPerformed

    private void next4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next4ActionPerformed
        if (queue.size() == 0)
            javax.swing.JOptionPane.showMessageDialog(null, "No tickets in the waiting queue");
        else {
            String counter_4_num_ticket = queue.dequeue();
            counter4.enqueue(counter_4_num_ticket);
            counter_4_num.setText(counter_4_num_ticket);
            latest_serving_num.setText(counter_4_num_ticket);
            counter_4_status.setForeground(java.awt.Color.red);
            comp_curr4.setEnabled(true);
            goOffline4.setEnabled(false);
            next4.setEnabled(false);
        }
    }//GEN-LAST:event_next4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cmPanel;
    private javax.swing.JDesktopPane cm_counter1;
    private javax.swing.JDesktopPane cm_counter2;
    private javax.swing.JDesktopPane cm_counter3;
    private javax.swing.JDesktopPane cm_counter4;
    private javax.swing.JButton comp_curr1;
    private javax.swing.JButton comp_curr2;
    private javax.swing.JButton comp_curr3;
    private javax.swing.JButton comp_curr4;
    private javax.swing.JLabel counter_1_label;
    private javax.swing.JLabel counter_1_num;
    public javax.swing.JLabel counter_1_status;
    private javax.swing.JLabel counter_2_label;
    private javax.swing.JLabel counter_2_num;
    public javax.swing.JLabel counter_2_status;
    private javax.swing.JLabel counter_3_label;
    private javax.swing.JLabel counter_3_num;
    public javax.swing.JLabel counter_3_status;
    private javax.swing.JLabel counter_4_label;
    private javax.swing.JLabel counter_4_num;
    public javax.swing.JLabel counter_4_status;
    private javax.swing.JPanel cvPanel;
    private javax.swing.JDesktopPane cv_counter1;
    private javax.swing.JDesktopPane cv_counter2;
    private javax.swing.JDesktopPane cv_counter3;
    private javax.swing.JDesktopPane cv_counter4;
    private javax.swing.JToggleButton goOffline1;
    private javax.swing.JToggleButton goOffline2;
    private javax.swing.JToggleButton goOffline3;
    private javax.swing.JToggleButton goOffline4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel last_issued_num;
    private javax.swing.JLabel latest_serving_num;
    private javax.swing.JTabbedPane menuTab;
    private javax.swing.JButton next1;
    private javax.swing.JButton next2;
    private javax.swing.JButton next3;
    private javax.swing.JButton next4;
    private javax.swing.JButton numButton;
    private javax.swing.JDesktopPane numberTicket;
    // End of variables declaration//GEN-END:variables
}
